version: "3"
volumes:
  pg_data:
services:
  api:
    build:
      context: api
    hostname: api
    restart: unless-stopped
    volumes:
      - ./api/app:/app
      - ./templates:/templates
      - ./data:/data
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:15-bookworm
    hostname: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
