# Generated by Django 5.2.4 on 2025-07-21 19:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUBMITTED', 'SUBMITTED'), ('RUNNING', 'RUNNING'), ('ERROR', 'ERROR')], default='QUEUED', max_length=20)),
                ('action', models.TextField(choices=[('ADD', 'ADD'), ('MODIFY', 'MODIFY'), ('CANCEL', 'CANCEL'), ('RELEASE', 'RELEASE')], default='ADD')),
                ('template', models.CharField(blank=True, default='default', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('ignore', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('study', 'study'), ('sample', 'sample'), ('experiment', 'experiment'), ('run', 'run')], max_length=10), blank=True, null=True, size=None)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('submission', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('raw_submission', models.TextField(blank=True, null=True)),
                ('raw_result', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(choices=[('bam', 'bam'), ('cram', 'cram'), ('fastq', 'fastq')])),
                ('md5sum', models.CharField(max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_files', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('QUEUED', 'QUEUED'), ('SUBMITTED', 'SUBMITTED'), ('ERROR', 'ERROR')], default='DRAFT', max_length=20)),
                ('template', models.CharField(blank=True, default='default', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('raw_result', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('FASTA', 'FASTA'), ('CHROMOSOME_LIST', 'CHROMOSOME_LIST'), ('FLATFILE', 'FLATFILE'), ('AGP', 'AGP'), ('UNLOCALISED_LIST', 'UNLOCALISED_LIST'), ('BAM', 'BAM'), ('CRAM', 'CRAM'), ('FASTQ', 'FASTQ')])),
                ('md5sum', models.CharField(max_length=32)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysisjob_files', to='core.analysisjob')),
            ],
            options={
                'unique_together': {('job', 'file_name')},
            },
        ),
    ]
