# Generated by Django 4.2.7 on 2023-11-22 08:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUBMITTED', 'SUBMITTED'), ('ERROR', 'ERROR')], default='QUEUED', max_length=20)),
                ('action', models.TextField(choices=[('ADD', 'ADD'), ('MODIFY', 'MODIFY'), ('CANCEL', 'CANCEL'), ('RELEASE', 'RELEASE')])),
                ('template', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.JSONField()),
                ('ignore', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('study', 'study'), ('sample', 'sample'), ('experiment', 'experiment'), ('run', 'run')], max_length=10), blank=True, null=True, size=None)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('submission', models.JSONField(null=True)),
                ('result', models.JSONField(null=True)),
                ('raw_submission', models.TextField(null=True)),
                ('raw_result', models.TextField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(choices=[('bam', 'bam'), ('cram', 'cram'), ('fastq', 'fastq')])),
                ('md5sum', models.CharField(max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_files', to='core.job')),
            ],
        ),
    ]
