# Generated by Django 4.2.7 on 2023-11-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='core.job'),
        ),
    ]
