# Generated by Django 4.2.7 on 2023-11-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_job_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.job'),
        ),
    ]
