# Generated by Django 4.2.7 on 2023-11-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='template',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
