# Generated by Django 4.2.7 on 2023-11-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_job_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='config',
            new_name='data',
        ),
    ]
