# Generated by Django 4.2.7 on 2023-11-24 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_config_job_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUBMITTED', 'SUBMITTED'), ('ERROR', 'ERROR')], default='QUEUED', max_length=20)),
                ('template', models.CharField(blank=True, default='default', max_length=50)),
                ('data', models.JSONField()),
                ('result', models.JSONField(null=True)),
                ('raw_result', models.TextField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.job')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(choices=[('FASTA', 'FASTA'), ('CHROMOSOME_LIST', 'CHROMOSOME_LIST'), ('FLATFILE', 'FLATFILE'), ('AGP', 'AGP'), ('UNLOCALISED_LIST', 'UNLOCALISED_LIST'), ('BAM', 'BAM'), ('CRAM', 'CRAM'), ('FASTQ', 'FASTQ')])),
                ('md5sum', models.CharField(max_length=32)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisjob_files', to='core.analysisjob')),
            ],
        ),
    ]
