# Generated by Django 4.2.7 on 2023-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_analysisjob_analysisfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='analysisfile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='analysisfile',
            unique_together={('job', 'file_name')},
        ),
    ]
