# Generated by Django 4.2.7 on 2023-11-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_analysisjob_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfile',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysisjob_files', to='core.analysisjob'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('SUBMITTED', 'SUBMITTED'), ('RUNNING', 'RUNNING'), ('ERROR', 'ERROR')], default='QUEUED', max_length=20),
        ),
    ]
