# Generated by Django 4.2.7 on 2023-11-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_analysisjob_data_alter_analysisjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
